name: Code Test
on:
  pull_request:
    branches: [ master ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: supercharge/mongodb-github-action@1.3.0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
